### ISSUE TITLE
Segfault in master when theme is invalid - "expanderInconsistent.png" not found!

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2991]
As reported here:
http://rawtherapee.com/forum/viewtopic.php?p=44287#p44287

RawTherapee 4.2.487 master in Fedora 22 from Fedora's repo segfaults on launch because it can't find expanderInconsistent.png

The repo gets the build from:
http://download.opensuse.org/repositories/home:/rawtherapee/Fedora_23/x86_64/

**Comment by Beep6581** [comment]
rawtherapee-4.2.487-1.1.x86_64.rpm includes this icon along with the other expander icons in the following path:
```
/usr/share/rawtherapee/images/Light/actions/expanderInconsistent.png
/usr/share/rawtherapee/images/Dark/actions/expanderInconsistent.png
```

Please install both `rawtherapee-4.2.487` and `rawtherapee-debuginfo-4.2.487` then run RT through GDB and send us a stack-backtrace, as described here: http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by mbajor** [comment]
Can't confirm this issue on Fedora 22 (Virtual Box).

**Comment by Beep6581** [comment]
Can't confirm = can't reproduce?

**Comment by mbajor** [comment]
Yes, RT installed from the repo works fine.

**Comment by Coasting** [comment]
I did the simple thing of renaming the Rawtherapee* folders in .config and the repo version of 4.2.487 came up fine creating, a new RawTherapee folder with a new options file. 

I then renamed that /.config/RawTherapee folder, dnf-removed 4.2.487, dnf-installed RT-gtk 4.2.526 and it ran fine. 

Finally, I dnf-removed RT-gtk3 4.2.526, left the /.config/RawTherapee folder intact, dnf-installed RT 4.2.487. It failed to run with the RT-gtk 4.2.526 version of .config, throwing the error:  

"expanderInconsistent.png" not found!
terminate called after throwing an instance of 'Glib::FileError'

Disabling the options file by renaming it allowed RT 4.2.487 to run fine without a problem, creating a new options file.

[options-487.txt](https://github.com/Beep6581/RawTherapee/files/46330/options-487.txt)
[options-526.txt](https://github.com/Beep6581/RawTherapee/files/46331/options-526.txt)

The two files differ slightly and that's probably a good clue. Perhaps a test of how different the versions are could trigger a deletion/change of the options file before trying to use options settings that cause a failure. Maybe something as basic as different branches get new options files. 

If you still think you need a debug backtrace it will probably be next week sometime before I can get to that. Life is intruding.

Don

**Comment by Beep6581** [comment]
That was... difficult to follow :]
Sounds like RT-gtk3 runs fine always, but RT-master (Gtk+ 2) fails to run when the options file contains a `Theme=foo` entry where foo is not a valid Gtk+ 2 theme.

**Comment by Coasting** [comment]
Yeah, it is a lot of words in order to be precise. Maybe the next paragraph will clarify it.

I forced both versions of RT to make new RawTherepee folders in $HOME/.config by renaming previous versions before running them for the first time. Then I found that the options file created by rawtherapee-gtk3 (4.2.526) prevented rawtherapee (4.2.487) from running with the error documented above. 

My diff file is a little more complicated than just a different theme but it may be the theme that is the issue.
[differences-options.txt](https://github.com/Beep6581/RawTherapee/files/46382/differences-options.txt)

I am fine with it all right now for my personal use. I only did this to help others avoid a whole lot of effort to figure out what is happening. In over a hundred versions RT3 and RT4 over the years this is the first time I can remember that an old options file caused the program to fail to run. I have had several different RawTherapee folders left over as remnants in .config and I'll start paying closer attention to those myself.

**Comment by Beep6581** [comment]
```
#9  0x0000000000a03d0c in MyExpander::init () at /home/drslony/repo-rt/rtgui/guiutils.cc:474
No locals.
#10 0x00000000009502c9 in main (argc=1, argv=0x7fffffffdd18) at /home/drslony/repo-rt/rtgui/main.cc:304
        exname = "/home/drslony/repo-rt/build/debug/rawtherapee", '\000' <repeats 466 times>
        exePath = {static npos = 18446744073709551615, string_ = "/home/drslony/repo-rt/build/debug"}
        m = <incomplete type>
        icon_path = {static npos = 18446744073709551615, string_ = "/home/drslony/repo-rt/build/debug/./images"}
        rtWindow = 0x1514bf0
        defaultIconTheme = {pCppObject_ = 0x1f88810}
        settings = {pCppObject_ = 0x0}
```

**Comment by Beep6581** [comment]
This fixes it by changing the theme to 21-Gray-Gray if the current theme is invalid. Invalid in this case means that the specified theme does not resolve to a readable file.

```
diff --git a/rtgui/main.cc b/rtgui/main.cc
index bbfca0c..c2d990e 100644
--- a/rtgui/main.cc
+++ b/rtgui/main.cc
@@ -278,6 +278,12 @@ int main(int argc, char **argv)
 
     if (options.theme.empty()) {
         options.theme = "21-Gray-Gray";
+    } else {
+        std::string themeFile = argv0 + "/themes/" + options.theme + ".gtkrc";
+        if (!std::ifstream(themeFile)) {
+            printf ("%s %s\n%s\n", "Current theme in options file is invalid: ", options.theme.c_str(), "Changing to 21-Gray-Gray");
+            options.theme = "21-Gray-Gray";
+        }
     }
 
     if (!options.useSystemTheme) {
```

**Comment by Beep6581** [comment]
Ok to commit?

**Comment by sguyader** [comment]
This fix prevents me from compiling (tried for 32-bit Debug build with GCC 4.6.1, and 64-bit Release build with GCC 5.1.0):
```
Building CXX object rtgui/CMakeFiles/rth.dir/main.cc.obj
C:\Rawtherapee-sources\rtrepo\rtgui\main.cc: In function 'int main(int, char**)':
C:\Rawtherapee-sources\rtrepo\rtgui\main.cc:283:37: error: no matching function for call to 'std::basic_ifstream<char>::basic_ifstream(std::string&)'
C:\Rawtherapee-sources\rtrepo\rtgui\main.cc:283:37: note: candidates are:
p:\transfert\mingw32\bin\../lib/gcc/mingw32/4.6.1/include/c++/fstream:460:7: note: std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const char*, std::ios_base::openmode) [with _CharT = char, _Traits = std::char_traits<char>, std::ios_ba se::openmode = std::_Ios_Openmode]
p:\transfert\mingw32\bin\../lib/gcc/mingw32/4.6.1/include/c++/fstream:460:7: note:   no known conversion for argument 1 from 'std::string {aka std::basic_string <char>}' to 'const char*'
p:\transfert\mingw32\bin\../lib/gcc/mingw32/4.6.1/include/c++/fstream:446:7: note: std::basic_ifstream<_CharT, _Traits>::basic_ifstream() [with _CharT = char, _Traits = std::char_traits<char>]
p:\transfert\mingw32\bin\../lib/gcc/mingw32/4.6.1/include/c++/fstream:446:7: note:   candidate expects 0 arguments, 1 provided
p:\transfert\mingw32\bin\../lib/gcc/mingw32/4.6.1/include/c++/fstream:420:11: note: std::basic_ifstream<char>::basic_ifstream(const std::basic_ifstream<char>&)
p:\transfert\mingw32\bin\../lib/gcc/mingw32/4.6.1/include/c++/fstream:420:11: note:   no known conversion for argument 1 from 'std::string {aka std::basic_string<char>}' to 'const std::basic_ifstream<char>&'
mingw32-make.exe[2]: *** [rtgui/CMakeFiles/rth.dir/main.cc.obj] Error 1
mingw32-make.exe[1]: *** [rtgui/CMakeFiles/rth.dir/all] Error 2
mingw32-make.exe: *** [all] Error 2
```

And:
```
C:\Rawtherapee-sources\rtrepo\rtgui\main.cc: In function 'int main(int, char**)':
C:\Rawtherapee-sources\rtrepo\rtgui\main.cc:283:37: error: no matching function for call to 'std::basic_ifstream<char>::basic_ifstream(std::string&)'
         if (!std::ifstream(themeFile)) {
                                     ^
In file included from C:\Rawtherapee-sources\rtrepo\rtgui\curveeditorgroup.h:23:0,
                 from C:\Rawtherapee-sources\rtrepo\rtgui\tonecurve.h:26,
                 from C:\Rawtherapee-sources\rtrepo\rtgui\toolpanelcoord.h:31,
                 from C:\Rawtherapee-sources\rtrepo\rtgui\batchtoolpanelcoord.h:23,
                 from C:\Rawtherapee-sources\rtrepo\rtgui\filepanel.h:23,
                 from C:\Rawtherapee-sources\rtrepo\rtgui\rtwindow.h:22,
                 from C:\Rawtherapee-sources\rtrepo\rtgui\main.cc:37:
P:/Transfert/MinGW64/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/fstream:495:7: note: candidate: std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
       basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
       ^
P:/Transfert/MinGW64/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/fstream:495:7: note:   no known conversion for argument 1 from 'std::string {aka std::basic_string<char>}' to 'const char*'
P:/Transfert/MinGW64/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/fstream:481:7: note: candidate: std::basic_ifstream<_CharT, _Traits>::basic_ifstream() [with _CharT = char; _Traits = std::char_traits<char>]
       basic_ifstream() : __istream_type(), _M_filebuf()
       ^
P:/Transfert/MinGW64/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/fstream:481:7: note:   candidate expects 0 arguments, 1 provided
P:/Transfert/MinGW64/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/fstream:455:11: note: candidate: std::basic_ifstream<char>::basic_ifstream(const std::basic_if
stream<char>&)
     class basic_ifstream : public basic_istream<_CharT, _Traits>
           ^
P:/Transfert/MinGW64/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/fstream:455:11: note:   no known conversion for argument 1 from 'std::string {aka std::basic_string<char>}' to 'const std::basic_ifstream<char>&'rtgui\CMakeFiles\rth.dir\build.make:1989: recipe for target 'rtgui/CMakeFiles/rth.dir/main.cc.obj' failed
mingw32-make.exe[2]: *** [rtgui/CMakeFiles/rth.dir/main.cc.obj] Error 1
mingw32-make.exe[2]: *** Waiting for unfinished jobs....
CMakeFiles\Makefile2:212: recipe for target 'rtgui/CMakeFiles/rth.dir/all' failed
mingw32-make.exe[1]: *** [rtgui/CMakeFiles/rth.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2
```

**Comment by heckflosse** [comment]
I fixed it a minute ago :)

**Comment by Beep6581** [comment]
That's your punishment for not testing :P

**Comment by heckflosse** [comment]
:)

**Comment by sguyader** [comment]
OK!
