### ISSUE TITLE
RawTherapee fails to build on Debian 9 from dev with commit 73655b6 (Dec 20, 2019)

### ISSUE THREAD

**Issue by abertens** [Beep6581/RawTherapee#5578]
Hi there,

RawTherapee does not build anymore on Debian 9 from git/dev due to commit 73655b6099e760446df86f29d572624aa4daa0ad "Merge pull request #5567 from Beep6581/help-btn"  (Dec 20, 2019).

Error is:

[ 43%] Building CXX object rtgui/CMakeFiles/rth.dir/rtwindow.cc.o
/tmp/rawtherapee-git-20191220/rtgui/rtwindow.cc: In member function ‘void RTWindow::showRawPedia()’:
/tmp/rawtherapee-git-20191220/rtgui/rtwindow.cc:924:67: error: ‘show_uri’ was not declared in this scope
     show_uri("https://rawpedia.rawtherapee.com/", GDK_CURRENT_TIME);
                                                                   ^
rtgui/CMakeFiles/rth.dir/build.make:1622: recipe for target 'rtgui/CMakeFiles/rth.dir/rtwindow.cc.o' failed
make[2]: *** [rtgui/CMakeFiles/rth.dir/rtwindow.cc.o] Error 1
CMakeFiles/Makefile2:242: recipe for target 'rtgui/CMakeFiles/rth.dir/all' failed
make[1]: *** [rtgui/CMakeFiles/rth.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Regards,
Andres Bertens

**Comment by abertens** [comment]
Previous built version info:

Version: 5.7-369-g5face2e44
Branch: 5.7-369-g5face2e44
Commit: 5face2e44
Commit date: 2019-12-20
Compiler: cc 6.3.0
Processor: generic
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: Release
Build flags:  -std=c++11  -Werror=unused-label -Werror=delete-incomplete -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON

**Comment by Floessie** [comment]
Confirmed. `show_uri()` is new in gtkmm 3.24 and Debian 9 has 3.22. Here's a possible workaround:

```patch
diff --git a/rtgui/rtwindow.cc b/rtgui/rtwindow.cc
index 4c6dc753f..514685a16 100644
--- a/rtgui/rtwindow.cc
+++ b/rtgui/rtwindow.cc
@@ -921,7 +921,8 @@ void RTWindow::writeToolExpandedStatus (std::vector<int> &tpOpen)
 
 void RTWindow::showRawPedia()
 {
-    show_uri("https://rawpedia.rawtherapee.com/", GDK_CURRENT_TIME);
+    GError* gerror = nullptr;
+    gtk_show_uri(nullptr, "https://rawpedia.rawtherapee.com/", GDK_CURRENT_TIME, &gerror);
 }
 
 void RTWindow::showICCProfileCreator ()
```

**Comment by abertens** [comment]
@Floessie 

With your workaround it builds and button opens Firefox with rawpedia page.

Thank you!

**Comment by TechXavAL** [comment]
It fails to build on Linux Mint 19.3 (Ubuntu 18.04) too (the available and installed gtkmm is 3.22).

The workaround works here, too.

But if you have set other browser than the default in the html filetype dialog **Properties>Open with>Default Application**, then the _new_ default browser opens, but doesn't show Rawpedia.

If you set again the html Default Application the same as the system wide default browser, then everything works as expected.
