### ISSUE TITLE
Build failure with GCC 9.0.1

### ISSUE THREAD

**Issue by mattiaverga** [Beep6581/RawTherapee#5177]
Fedora official repository just switched to GCC 9.0.1 and now RT fails to build due to several `enclosing 'parallel'` errors. See the build log at:
https://kojipkgs.fedoraproject.org//work/tasks/1333/32821333/build.log

**Comment by mattiaverga** [comment]
I've found other packages in Fedora affected by this and in mailing lists I could found a link to a GCC related change: https://gcc.gnu.org/gcc-9/porting_to.html#ompdatasharing

**Comment by Floessie** [comment]
Hi Mattia,

Thanks for the bug report! I'll try to reproduce this in Debian Experimental.

Best,
Flössie

**Comment by Floessie** [comment]
Now it builds fine with GCC 9.0.1:

```patch
diff --git a/rtengine/demosaic_algos.cc b/rtengine/demosaic_algos.cc
index 617feb3b4..18e338a70 100644
--- a/rtengine/demosaic_algos.cc
+++ b/rtengine/demosaic_algos.cc
@@ -1159,7 +1159,7 @@ void RawImageSource::igv_interpolate(int winw, int winh)
     }
 
 #ifdef _OPENMP
-    #pragma omp parallel default(none) shared(rgb,vdif,hdif,chr)
+    #pragma omp parallel default(none) shared(width,height,v1,v2,v3,v5,rgb,vdif,hdif,chr)
 #endif
     {
         __m128 ngv, egv, wgv, sgv, nvv, evv, wvv, svv, nwgv, negv, swgv, segv, nwvv, nevv, swvv, sevv, tempv, temp1v, temp2v, temp3v, temp4v, temp5v, temp6v, temp7v, temp8v;
```

@heckflosse Okay? Or drop the `default(none)`?

**Comment by heckflosse** [comment]
@Floessie your patch fails on gcc < 9.0
```
Z:/H2/rt55_fix/rtengine/demosaic_algos.cc: In member function 'void rtengine::RawImageSource::igv_interpolate(int, int)':
Z:/H2/rt55_fix/rtengine/demosaic_algos.cc:1162:90: error: 'v5' is predetermined 'shared' for 'shared'
     #pragma omp parallel default(none) shared(width,height,v1,v2,v3,v5,rgb,vdif,hdif,chr)
                                                                                          ^
Z:/H2/rt55_fix/rtengine/demosaic_algos.cc:1162:90: error: 'v3' is predetermined 'shared' for 'shared'
Z:/H2/rt55_fix/rtengine/demosaic_algos.cc:1162:90: error: 'v2' is predetermined 'shared' for 'shared'
Z:/H2/rt55_fix/rtengine/demosaic_algos.cc:1162:90: error: 'v1' is predetermined 'shared' for 'shared'
Z:/H2/rt55_fix/rtengine/demosaic_algos.cc:1162:90: error: 'height' is predetermined 'shared' for 'shared'
Z:/H2/rt55_fix/rtengine/demosaic_algos.cc:1162:90: error: 'width' is predetermined 'shared' for 'shared'
```
Dropping `default(none)` works

**Comment by Floessie** [comment]
I should have double checked. :facepalm:

So do we drop `default(none)` only in this place or the two other places, too?

**Comment by heckflosse** [comment]
Drop the other two places too.

**Comment by Floessie** [comment]
Here's the new patch:

```patch
diff --git a/rtengine/demosaic_algos.cc b/rtengine/demosaic_algos.cc
index 617feb3b4..7339981e5 100644
--- a/rtengine/demosaic_algos.cc
+++ b/rtengine/demosaic_algos.cc
@@ -388,7 +388,7 @@ void RawImageSource::jdl_interpolate_omp()  // from "Lassus"
     }
 
 #ifdef _OPENMP
-    #pragma omp parallel default(none) shared(image,width,height,u,w,v,y,x,z,dif,chr) private(row,col,f,g,indx,c,d,i)
+    #pragma omp parallel shared(image,width,height,u,w,v,y,x,z,dif,chr) private(row,col,f,g,indx,c,d,i)
 #endif
     {
 #ifdef _OPENMP
@@ -1159,7 +1159,7 @@ void RawImageSource::igv_interpolate(int winw, int winh)
     }
 
 #ifdef _OPENMP
-    #pragma omp parallel default(none) shared(rgb,vdif,hdif,chr)
+    #pragma omp parallel shared(rgb,vdif,hdif,chr)
 #endif
     {
         __m128 ngv, egv, wgv, sgv, nvv, evv, wvv, svv, nwgv, negv, swgv, segv, nwvv, nevv, swvv, sevv, tempv, temp1v, temp2v, temp3v, temp4v, temp5v, temp6v, temp7v, temp8v;
@@ -1548,7 +1548,7 @@ void RawImageSource::igv_interpolate(int winw, int winh)
     }
 
 #ifdef _OPENMP
-    #pragma omp parallel default(none) shared(rgb,vdif,hdif,chr)
+    #pragma omp parallel shared(rgb,vdif,hdif,chr)
 #endif
     {
 
```

Tested this time with GCC 9.0.1, GCC 8.2, Clang 9.0.0, and Clang 7.0.1 on Debian Testing/Experimental amd64.

**Comment by Beep6581** [comment]
No problem building using GCC-7.3.0 C++11.

**Comment by mattiaverga** [comment]
Builds fine on Fedora also with both GCC 8.2.1 and GCC 9.0.1

Thanks

**Comment by gaaned92** [comment]
builds fine on W64 MSYS2 gcc8.2.1

**Comment by gaaned92** [comment]
builds fine on W64 MSYS2 gcc 8.2.1
