### ISSUE TITLE
Improvements related to the GUI - Movable tools

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2631]
Originally reported on Google Code with ID 2648

```
Hello, I am coding a few improvements for the gui,
they should arrive via a big patch in a few weeks:

This is partially related to https://code.google.com/p/rawtherapee/issues/detail?id=1578

But still, it came from here: http://rawtherapee.com/forum/viewtopic.php?f=2&t=5848


What's going to be on it?

Summary:
* Favorite tab. (for putting a few tabs in favorite so you don't have to browse and
search your most used tool each time you want to do an usual process.)
* Trash tab.(if you want to hide some unused tools from the panel.)
* Vertical reordering of tools.
* Horizontal reordering of tools. (meaning you can move them to another panel).
* Displaying of information on label of each tool. (active / position of the filter
etc.)
* Allow to change the colors of all tools in a panel. (It might include a gradiant
variation...)
* Allow to change the colors of a given tool.
* Change the background color of a given tool when it is not active. (by ligthening
it or darkening it).
* Allow to save the corresponding settings to a new theme system, so it does not interact
with profile.
* Allow to reload those setting.

I am halfway done in the coding, asides from a few strings to add in localization,
the changes should impact mostly those files:
* rtgui/toolpanel.cc
* rtgui/toolpanel.h
* rtgui/toolpanelcoord.cc
* rtgui/toolpanelcoord.h

There are improvements to the object and methods of those files, mostly by adding new
methods to cover the needs.
```

Reported by `tennevin.yves` on 2015-01-27 22:03:01

**Comment by Beep6581** [comment]
tennevin.yves missing in action. I'll email him and we can continue in a new issue if he's still on board.

**Comment by esby** [comment]
Hello, 

I had some time for coding, made some progress, ported my old code to the most recent code from github. (I was still on the irc channel; but had no time to code until one month ago...)

I forked the default branch  on my own repositery. 
https://github.com/esby/RawTherapee

It is working under linux (debian 8.6), still it's untested under the other platforms.

It's not perfect for now, consider it as a 'functional demo'. 

I still have one issue to handle, I need to do some post operations steps at some point, once the gui is fully loaded, but still there is a slowness when the gui is in mutliple editors mode.

Basically, when the application starts in multiple editors mode, the tabs are taking more time to load. (depending of the computer speed). I assume I need to trigger the associated code on the latest  possible time which is not probably not happening correctly for now.

The current code is also not thread locked, so I don't really know how this is safe or not.

There might still be some bugs to fix or some settings to tweak.

The icons are in png format, not svg counterparts exists for now.
(the png are either simple enough to be public domain still or are coming from commons site under a free licence, when they are not my own creation.) Other icons can probably be made if needed, but this is not this this post subject.

The translation are defined in the code but not necessarily in the default file. I believe this is not this post subject either.

The ttp file loading (in charge for loading / saving the gui modifications externally from the pp3 files) might not be safe enough to import external and possibly unsafe ttp files. I'll probably need to verify that part before any code is pulled back to the original project.

In terms of features:
* Three more tabs to the editor panel:
** one favorite tab. which will contains the tools that are 'favorited'.
** one trash tab. which will contains the tools that are 'trashed'.
** one useful tab which contains various tool, mainly to configure the gui; add some colors (this might be not strictly compliant with gtk themes, but it might be easier than modifying the gtk theme.) / hide / shows some buttons per tool, save and load the associated tools  outside of the post processing settings. (This is needed because hiding some tool or moving them should not be recorder in the pp3 files.)

* When a tool is 'favorited', it will appears when the favorite tabs is activated, it will be back on its original tabs if this tab get displayed. 
* When a tool is 'trashed', it will disappears from the original tab, but it will appear on the favorite tab if it was favorited. it can be enabled again by displaying the trash tab.

* Tabs can be hidden, either by the tool panel, either by the preference panel, enabling / disabling these in preference panel will require a restart. 

* The tools can be moved / reordered in the tabs, either vertically (up / bottom) or horizontally (left / right), meaning you could theorically put the whitebalance tool in the exposure tabs if you needed to.

* The buttons to move and to put to favorite / trash tabs can be locked / hidden if needed, so a configuration can be locked and saved as once got created.

* Some settings are written to the option file, mainly the autoload of gui profiles (.ttp files), showing and hiding of tabs. 

If you have comments or opinions on it.
I'll try to make the code as separate class as much as possible. Probably by playing on the ancestor inheritance. 

The actual modifified guy can looks like that. 

![rt-tab-favorite-preview](https://cloud.githubusercontent.com/assets/277296/19159608/63b48d12-8bed-11e6-824c-70454703a4f4.png) (the wavelet tab is absent because i chose to hide it.)

**Comment by sguyader** [comment]
Hi, trying to compile your branch now in Linux, I get the following error at the end of compilation:
`[ 98%] Building CXX object rtgui/CMakeFiles/rth.dir/ttpanelcolorer.cc.o
/home/sguyader/rt-sources/rtrepo-newtest/rtgui/ttsaver.cc: In member function ‘void TTSaver::themeSplitter(std::ifstream&)’:
/home/sguyader/rt-sources/rtrepo-newtest/rtgui/ttsaver.cc:213:37: error: cannot convert ‘std::basic_istream<char>’ to ‘bool’ in assignment
     condition = getline (myfile,line);
                                     ^
/home/sguyader/rt-sources/rtrepo-newtest/rtgui/ttsaver.cc: In member function ‘virtual void TTSaver::themeImport(std::ifstream&)’:
/home/sguyader/rt-sources/rtrepo-newtest/rtgui/ttsaver.cc:459:37: error: cannot convert ‘std::basic_istream<char>’ to ‘bool’ in assignment
     condition = getline (myfile,line);
                                     ^
make[2]: *** [rtgui/CMakeFiles/rth.dir/build.make:3255: rtgui/CMakeFiles/rth.dir/ttsaver.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/sguyader/rt-sources/rtrepo-newtest/rtgui/ttfavoritecolorer.cc: In member function ‘virtual void TTFavoriteColorChooser::themeImport(std::ifstream&)’:
/home/sguyader/rt-sources/rtrepo-newtest/rtgui/ttfavoritecolorer.cc:188:37: error: cannot convert ‘std::basic_istream<char>’ to ‘bool’ in assignment
     condition = getline (myfile,line);
                                     ^
make[2]: *** [rtgui/CMakeFiles/rth.dir/build.make:3279: rtgui/CMakeFiles/rth.dir/ttfavoritecolorer.cc.o] Error 1
/home/sguyader/rt-sources/rtrepo-newtest/rtgui/ttpanelcolorer.cc: In member function ‘virtual void TTPanelColorChooser::themeImport(std::ifstream&)’:
/home/sguyader/rt-sources/rtrepo-newtest/rtgui/ttpanelcolorer.cc:327:37: error: cannot convert ‘std::basic_istream<char>’ to ‘bool’ in assignment
     condition = getline (myfile,line);
                                     ^
make[2]: *** [rtgui/CMakeFiles/rth.dir/build.make:3303: rtgui/CMakeFiles/rth.dir/ttpanelcolorer.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:236: rtgui/CMakeFiles/rth.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
mv: cannot stat 'release/': No such file or directory
`

Here's some info regarding my Linux box:
`cat /proc/version
Linux version 4.6.7-1-MANJARO (builduser@manjaro) (gcc version 6.1.1 20160802 (GCC) ) #1 SMP PREEMPT Tue Aug 16 19:20:55 UTC 2016
`

**Comment by esby** [comment]
This seems related to gcc version and C++11. 
I am using gcc 4.9.
I don't have access to gcc 6.X so I can't really test, I assume there is an explicit cast needed from other post on internet ( http://stackoverflow.com/questions/23364606/istream-to-bool-conversion-when-is-it-available ) 

I updated the code, can you try again? (not sure if it needs a (bool) gettline(...) or a bool( getline(...) ) fix still. the first version compiles here.)

**Comment by mks9900** [comment]
@esby: Great work! It compiles fine here now using gcc 5.4 and I took it for a test drive.
I really like what you have done here! There are some quirks, but I think this will be awesome!
Thanks a lot!

**Comment by sguyader** [comment]
@esby Yves, with your last changes it now compiles fine with gcc 6.1.1.
The possibility to add tools to a "favorites" tab is a very, very useful addition, thanks for working on this.

Some remarks.
I see that in the options you can toggle the color of the favorite tools, I think it would be better to have the color to be automatically toggled when the tool is added to Favorites, as most users would find it useful.
I like the possibility to reorder the tools in the Favorites tab, but I don't see its usefulness in the main tabs. Also, I don't see why one would use the right/left arrows to move the tools from one tab to the other (for example, I would not want to move the "Vibrance" tool to another tab such as "Wavelet"). And if by mistake we click on a right/left arrow, without noticing it, we could loose some time searching where the tool has gone.
So, I would suggest simply removing these right/left arrows, and it would also make the space less cluttered with buttons.

**Comment by Floessie** [comment]
@esby 
>  updated the code, can you try again? (not sure if it needs a (bool) gettline(...) or a bool( getline(...) ) fix still. the first version compiles here.)

Hm, we are programming in C++, aren't we? So it would be really cool to use C++ style casts instead of C style ones. A `static_cast<bool>(...)` would be appropriate here. :wink:

HTH
Flössie

**Comment by heckflosse** [comment]
@esby Builds fine on Win7/64 using gcc 5.3 :+1: 
I'll test it now

**Comment by esby** [comment]
@Floessie I'll fix that when I can. Honestly, I learned C++ by hacking things together, so I have no real bases of it. As long it compiles and works, it suits me, if there are best practice I'll gladly apply these.

@sguyader : for moving the elements in all 'directions', the idea was that the user could do something completely different. like reorganizing all tabs for its needs. So one could go multiple tabs with one tool per tabs for example. The logic to have thematic tabs like we have is not necessarily the only one. This was an extreme example, but one could put the tools he uses oftenly in an higher placement than the ones he uses less. Eg: in Details Panels he could put the noise reduction and the impulse noise reduction first over the others, while not necessary hiding the others.

**Comment by esby** [comment]
@Floessie fixed.

**Comment by heckflosse** [comment]
@esby I wonder why it takes so long to switch tabs on my 4 Ghz cpu (in SETM). Can you point me to the related code?

**Comment by esby** [comment]
@heckflosse 

in rtgui/toolpanelcoordinator.cc

ToolPanelCoordinator::on_notebook_switch_page(...)

The performance issue affecting multiple editor startup is probably linked to it.
I ain't sure this is directly linked to the code.

There is also one part in 
rtgui/toolpanel.cc
void ToolPanel::favorite_others_tabs_switch() 
(...)

The code could probably be optimised more,
 as it checks affects all the panels and not the ones being changed specifically.
It also moves some panels depending the various cases:
* if an evaluated panel is  (favorited / trashed).
* if the notebook got switched from (favorite or trash tabs) <-> (any tabs). (which mans normal tabs <-> normal tabs should not have performance issue due to it.)

**Comment by esby** [comment]
@heckflosse 

Un the current algorithm, there are two distincts cases:

* the panels that get changed (favorited / unfavorited , trashed / untrashed ).
* the panels that needs to be switched back when a tab is displayed: a panel cannot be attached or displayed at two distinct places in gtk. The current trick is to move the panels and replace them by a dummy panel to keep the positions when the tabs are switched.  If the tabs are switched back, the panel and its dummy variant will be permuted again. 

Which means that ideally, it should lead to two distinct but complementary strategies:

* Parse all panels, determine which one needs an update, create a property or a list so these panels can be handled at some points.

* parse all panels that are affected by a tab switch and only these.

The current implementation is not like that, at it parses almost all the time every panels, it is not very cpu friendly.

Right now I don't have time to code, I am going to a local convention in France (in Annecy from Toulon); so my week-end is already booked. But i'll probably have some free time in the next week to correct and improve the situation.

**Comment by esby** [comment]
@heckflosse I fixed the issue, it was easier than I thought, but still there might be some other issues to correct. (there is actually one, but it's not triggerable right now, if a ttp profile is created and loaded later with a new version which contains  new panel(s), the possibly new panels that were not defined at this point wont be loaded.) I'll fix the logic for it.

**Comment by heckflosse** [comment]
@esby Yeah, that's much better :+1:

**Comment by esby** [comment]
Basic features:

* allow tools to be favorited or trashed (which hides them by moving them into the trash tab.)
* allow tools to be moved horizontally between tabs.
* allow tools to be moved or vertically inside a given tab.


Basic tweaks / fix:
* allow to test (play) the sounds defined in sound preferences inside the preference tab..
* the title is now divided into two areas: one for the title and one for the buttons (hide / show / and arrow keys), this is due to a bug while hovering on the title the old way. (it conflicted with buttons locked or visible.)

Features via utilitary tools (in the tool tab with an 'U'.):
Basically, each feature can be disabled or enabled .
* saving / (auto) loading of tt tool configuration via a ttp profile. They are saved in the user path profile.
* hiding / showing tabs.
* allow to change the color of the favorite / trash button for each tool..
* allow to change the color of the title of each tool.
* allow to lock the favorite trash button.
* allow to hide or show the arrow key to move each tool
* allow to auto click on auto distorsion_correction.
(this won't work in batch processing, this is just intended to avoid clicking on the button each time you load an image or a profile.)
* allow to exit the application after saving an image in single editor mode.

Code impact:
* a few files are heavily impacted:
** toolpanel.*
** toolpanelcoord.*

* some files are slightly impacted: a few lines added each time.

* some files are new:
** rtdef.h which contains forward declarations needed to avoid circular recursion issues,
which allow to impact less toolpanel.*

** toolvboxdef.* which contains another part of the code. (linked to the toolvbox.)
** environment.* which contains various data, which can be used by the tt tools.
** the tt tools, tt*.* which contains the underlying code for the tt tools. (the idea on the long run would be to make external tt tools that are dynamically loaded via dll / libs.)

There are probably a few bugs left and a few things to do:
* I suspect one bug with moving panels near the trash tab.
* there might be some code to change in toolpanelcoord.*
* I am probably going to reorganise a bit toolpanel.* and check that all methods are necessary.

I'll probably port the changes to the gtk3 version once it is release. I have no idea of what will be affected, but gtk3 will probably allow to create a few tt tools related to the interface. (colored components which are not really possible actually etc.)

If some people can test the new version; just to see if it works fine.
If there are remarks / suggestions, they are welcome.

**Comment by mks9900** [comment]
Hi @esby, I love this feature! However on RT exit all favourites are lost. Also, right clicking on a tool's header doesn't collapse all other tools as it does neatly in master.

**Comment by esby** [comment]
@mks9900 fir the first problem, it is because you are supposed to use the save button on the first tool on the utility tab, after saving you can configure an autoload.

For the second issue, I'll need to check it.

**Comment by esby** [comment]
Can't reproduce the second issue: right clicking seems to collapse properly the panels here.

**Comment by mks9900** [comment]
Ah, completely missed the save-part in all excitement ;-) Would it be possible to do without any saving? I'm thinking from a user stand point here; once rearranged, it should stay that way. You'll loose the option to have many different favourites and so, but imho it's better to keep it simple and straight forward. :-)

When I start RT, the saved file doesn't autoload, even though that option is ticked (TT_SAVER_AUTOLOAD_SETTINGS), and when I load it manually, then the tools doesn't collapse by right-clicking them... Is it just here or do you get the same?

Thanks again!

**Comment by esby** [comment]
Would it be possible to do without any saving?
I could be possible to  have an auto save on exit, but I personnaly hate when the software remembers a state I don't necessary want. (eg: I have done something wrong and I am now stuck with a setting I can't get rid of by exiting...)

When I start RT, the saved file doesn't autoload, even though that option is ticked

Could you tell me which os you are running it ? I assume you clicked and had something selected when you clicked the button ? Here, (debian 8.6), the tools did collapse when right clicking them.

**Comment by mks9900** [comment]
Sorry, for the late response... 
1. I understand your point! I was more on the user convenient (lazy?) path.. :-)
2. I run Gentoo Linux. As for the collapsing part, the Favourite-tab behaves differently than the other, e.g. the Exposure-tab (at least here): when I right-click on the Exposure-tab, each clicked tool is collapsed and expanded so that only one is visible at a time, while as in the Favourite-tab none of the tools collapses and they all end up being expanded.

Thanks again!

**Comment by esby** [comment]
@mks9900 : I think I know where this comes from, I'll fix that when I'll have some time, probably tomorrow.

**Comment by esby** [comment]
@mks9900 this should be fixed.

**Comment by mks9900** [comment]
@esby Great Yves, it works as you planned now! Thanks a lot! :+1:

**Comment by esby** [comment]
Hello, I've updated my fork to the dev branch code. (I assumed this was the one used to make rc candidate at some point, I havn't looked at the branch system used in details. Assuming I havn't made any error in the checkout tag I used  to sync (b3ee765bf) )

For the background, I only have time to code only a few months a year, mainly in december and in july / august; the rest of the time I can't really code.

Given the context, I also don't want to interact much in the dev context of RT, I am just writing the post to inform there is an existing fork tailored to my needs and that the code structure might / could be merged in main tree, as I don't know if this needs to be merged in the source tree or not, I doubt it because there are a lots of features which are experimental and tailored to my needs. I can maintain the code up to the dev tree, not sure if there is an interest to it (except for me), I am using the fork for my photo needs anyway.

Maybe i'll submit a patch to ease the maintainability of the fork (that will mainly affects rtgui/toolpanelcoordinator.cc/h files and maybe I can externalize the changes to more files)

Feel free to rip any features that could be implemented in the main tree if needed, 

-- 

Features added by the fork: (Those are only affecting the gui; not the internal processing code.)
* favorite / trash (which meaning hiding a panel) panel container (Gtk::tooVBox).
* tool moving by arrow button between any panel in vertical or horizontal direction. (horizontal is not possible in trash / favorite.)
* panel container hiding / showing (there are some bugs to correct here.), which means you'll be able to hide favorite, utility, trash or any container if you wish to (or display them back again.)
* an utility container which contains special tool that interacts with the gui. They are saved in their own configuration files (labeled as ttp) and are not bound to interact with pp3 profiles. Thinks of them as options that can be toggled into separate custom profile. The features in it are as follow for now:
** one tool for loading / saving associated profile.
** one tool for hiding showing panel container.
** two tool to change the color of tool label outside of the themes. I never use themes and I prefer this quick alternative.
* one tool to hide / show / lock / unlock the new buttons linked to the favorite and movable panels.
* one tool that allows to correct some issues I've found on rt since a while:
** auto clicking on auto distortion correction after a profile is loaded. (it won't work in batch mode, but one can load the image manually and then set them to process mode.)
** allow to close RT after an image has been saved in single editor mode.
** allow to reduce RT to icon in ME mode.
** allow to automatically resets the WhiteBalance for rt4 old pp3 settings in which the wb balance was garbled due to a change in the code.
* allow to correct automatically horizon for Panasonic Gh5 based on the roll angle exif value. I don't know if other cameras implements these features. The settings is limited to photo not taken in burst mode as the information is not reliable in burst mode (it is taking the value for the first photo taken.).
* allow to automatically select and apply a partial profile based on the exif isos values, so noise reduction can be applied independantly of the choosen profile. (the tool wiil switch to partial mode to apply the following profile then switch back to the original value, the partial folder are supposed to be located in (...)profiles/Partial paths (either system or user. I need to document it more.)

--

A few note about ttp profiles:
There are tool related profile not bound to processing. I felt this was needed because I don't want to have profiles interacting with the interface. I also don't want to mess in options, So I made a custom text based profile in which each line is parsed and given to the corresponding tool to configurate. Each tool configured this way is independant. This allows most features to be disabled if needed and to customize the interface against a given process and provides different interface according to  the process choosen.

--

Activating the features:
To use the features, you need to go in the Utility panel (the inverted U) and enable / disable which option you need, once that, you need to click on the save button of TP_SAVER_LABEL to create a given ttp profile, if you wish it to be autoloaded at the next startup of the tool (or at an image loaded), you need to enable the TTP_SAVER_AUTOLOAD_SETTINGS radio button while a profile is active in the combobox, this will write the names in option file and will load it.

For the iso profiler tool, you need to save a partial profile in Partial folder (create it if needed). you need to save only the value you needs to or edit them lately. Once you've done it, restart the application, you'll be able to create a lower iso treshhold, associate the value with any partial profile present then. basically if you create an iso limit of 200 and one of 400, the 200 one will be used for images that have values between 200 and 399. The 400 one will be used for values over 400 isos, this is not limited in number and can be configured for several threshold values. I've added 4 profiles as examples in the fork; they are the same and needs to be configurated to your needs.

--

There are no translation maintained for the corresponding interface, the code is too unstable to maintain it for now from my point of view for now.

-- 

Todo; 
* fix bugs (mainly linked with the hiding / showing of container boxes, this is actually a loading / saving issue)
* allow a drag & drop instead of the button system to move tools.

**Comment by heckflosse** [comment]
@esby Trying to open non RW2 raw files segfaults

**Comment by heckflosse** [comment]
@esby On Win7 when using METM I can open 6 images with your fork while in dev I can open 15 images.

**Comment by esby** [comment]
For the non RW2 raws, it should be fixed.

For the METM issue, I am assuming this is a memory issue ?

**Comment by heckflosse** [comment]
@esby 
> For the METM issue, I am assuming this is a memory issue ?

No, it's a problem with GDI handles on Windows.

```
Windows GDI handles in METM

                   dev         your fork
-------------------------------------------
rt started        1588           1588
1 image opened    2067           3524
2 images opened   2544           4423
3 images opened   3019           5324
```

**Comment by heckflosse** [comment]
@esby I really like the idea to use the `roll angle exif value`. How reliable is that value?
I tested with some shots (no burst mode) and it was not very reliable. But maybe I did something wrong. I don't own a Panasonic Camera and just tested with a few RW2 files I have...

If it's reliable, you could extend it to the first shot of a burst ;-)

**Comment by esby** [comment]
@heckflosse about the roll angle:
For burst mode, the camera does not seem to update the value during a burst, so it's unreliable in burst mode. Yes, for the first shot of the burst it might be reliable.

For posed shots, I assume it is reliable if you don't move that much.
I did a few samples twice just to check and the horizon was corrected each time.

I tried with a CR2 file from a canon 6D, which was taken in burst mode and the roll angle was not present apparently.

--

I am not sure of how gdi handles are handled by windows, Do gtk::widgets created by the tools needs to be deleted? I assumed they'll be deleted the instant the parent is deleted? There is a new class that lacked destructors, but still, I doubt it would affect the gdi handles. From what I know, a lots of widget are created for displaying the exif in the ttvardisplayertool, but I'd assume they'll be deleted the instant the window is closed? 

I am under linux (debian 9.6) and i never build rt for windows, so I can't really check it right now. I do have a windows xp virtual machine, but I don't even know if I'll be able to build rt under it.

--

I just pushed the changes for the non RW2 raws issue (it was linked to difference in exif of panasonic vs others camera maker, not sure why.)

**Comment by heckflosse** [comment]
@esby About the gdi handles: It's not a problem of not being deleted elements. It's just that the handles accumulate with the number of open editors in METM. Of course it's possible to open more than 6 images in METM, but not more than 6 at a time. Fortunately RT tells you that an image cant be opened and you have to close an Editor instance in case the GDI handle limit is reached.

**Comment by esby** [comment]
Oh, I see, 

Can you try to comment the 202th line at rtgui/toolpanelcoord.cc
 addPanel (usefulPanel, Gtk::manage (new TTVarDisplayer()));
->
// addPanel (usefulPanel, Gtk::manage (new TTVarDisplayer()));

and recompile to see if this helps?

**Comment by heckflosse** [comment]
That reduces the number of GDI handles per open editor by 4. There must be something different which needs so many handles...

Edit: I confirm that the segfault for non RW2 files is fixed :+1:

**Comment by esby** [comment]
@heckflosse I managed to install a windows 10 inside a vm, I'll try to hunt down the gdi handles. What do you use to measure the number of gdi handles ? I tried to use the task manager, but the number it outputs are looking different than yours.

**Comment by heckflosse** [comment]
@esby I used the task manager, but my numbers may be different because I'm on Win7.
This tool is also good
https://www.nirsoft.net/utils/gdi_handles.html

**Comment by esby** [comment]
@heckflosse : can you retry to see if the situation is better now ? 
I got a general question: should the "new Gtk::<object>" creation always "gtk managed"? 
Because I searched for instances not managed in the dev code and I found 39 instances which were created directly without Gtk::Manage I am assuming this will either leak or create gdi handles leaks

**Comment by Beep6581** [comment]
Closing as superseded by #5016 #5256
