### ISSUE TITLE
rawtherapee does not compile with clang on ubuntu 13.10

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2293]
Originally reported on Google Code with ID 2309

```
When trying to compile rawtherapee with clang 3.4 from repositories I get multiple errors
like this:

In file included from rtengine/iplab2rgb.cc:25:
rawtherapee/rtengine/../rtgui/icmpanel.h:75:14: error: no type named 'auto_ptr' in
namespace 'std'
        std::auto_ptr<FileChooserLastFolderPersister> ipDialogPersister;
        ~~~~~^

the same errors appear in the files:
rtgui/darkframe.h:41
rtgui/flatfield.h:42

The case of the error semms to be the following: by C++ standard, auto_ptr is defined
in header <memory>, which is not included in those files. But in these files there
is a suspicious inclusion of non-standart header <auto_ptr.h> if the compiler is not
clang: 

#ifndef __clang__
#include <auto_ptr.h>
#endif

If I include <memory>, everything compiles well with both gcc and clang.

Could anyone explain why it is done as it is now?

Ubuntu 13.10 64-bit
Ubuntu clang version 3.4-1ubuntu1 (trunk) (based on LLVM 3.4)
gcc version 4.8.1 (Ubuntu/Linaro 4.8.1-10ubuntu9) 
cmake version 2.8.11.2

rawtherapee: changeset:   2665:f354f91acd11

```

Reported by `ilia.b.popov` on 2014-03-24 12:01:56
