### ISSUE TITLE
glibmm 2.54 requires C++14

### ISSUE THREAD

**Issue by Floessie** [Beep6581/RawTherapee#4092]
After upgrading glibmm from 2.50.1 to 2.54.0 on Debian testing today, RT won't compile anymore:

```
In file included from /usr/include/glibmm-2.4/glibmm/containerhandle_shared.h:23:0,
                 from /usr/include/glibmm-2.4/glibmm/arrayhandle.h:21,
                 from /usr/include/glibmm-2.4/glibmm.h:92,
                 from /home/user/src/rawtherapee/rtexif/rtexif.h:30,
                 from /home/user/src/rawtherapee/rtexif/nikonattribs.cc:27:
/usr/include/glibmm-2.4/glibmm/variant.h:2012:24: error: ‘std::index_sequence’ has not been declared
                   std::index_sequence<Is...>)
                        ^~~~~~~~~~~~~~
/usr/include/glibmm-2.4/glibmm/variant.h:2012:38: error: expected ‘,’ or ‘...’ before ‘<’ token
                   std::index_sequence<Is...>)
                                      ^
/usr/include/glibmm-2.4/glibmm/variant.h: In static member function ‘static Glib::Variant<std::tuple<_Tps ...> > Glib::Variant<std::tuple<_Tps ...> >::create(const std::tuple<_Tps ...>&)’:
/usr/include/glibmm-2.4/glibmm/variant.h:2030:45: error: ‘index_sequence_for’ is not a member of ‘std’
   detail::expand_tuple(variants, data, std::index_sequence_for<Types...>{});
                                             ^~~~~~~~~~~~~~~~~~
/usr/include/glibmm-2.4/glibmm/variant.h:2030:69: error: expected primary-expression before ‘...’ token
   detail::expand_tuple(variants, data, std::index_sequence_for<Types...>{});
                                                                     ^~~
/usr/include/glibmm-2.4/glibmm/variant.h: At global scope:
/usr/include/glibmm-2.4/glibmm/variant.h:2073:71: error: ‘std::index_sequence’ has not been declared
 void assign_tuple(std::vector<VariantBase> &variants, Tuple & t, std::index_sequence<Is...>)
                                                                       ^~~~~~~~~~~~~~
/usr/include/glibmm-2.4/glibmm/variant.h:2073:85: error: expected ‘,’ or ‘...’ before ‘<’ token
 void assign_tuple(std::vector<VariantBase> &variants, Tuple & t, std::index_sequence<Is...>)
                                                                                     ^
```

[`std::index_sequence_for<>`](http://en.cppreference.com/w/cpp/utility/integer_sequence) is part of C++14 (a minor update to C++11), and compiling with C++14 enabled succeeds:

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 65ac4bdd..2075e35d 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -23,7 +23,7 @@ string(TOUPPER ${CMAKE_BUILD_TYPE} UPPER_CMAKE_BUILD_TYPE)
 
 # Set required C and C++ standards and check GCC version:
 SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c11")
-SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
+SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14")
 
 if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS "4.9")
     message(FATAL_ERROR "Building RawTherapee requires using GCC version 4.9 or higher!")
```

This might mean to lift the minimal GCC version to [5](https://gcc.gnu.org/projects/cxx-status.html#cxx14).

I didn't find a reference to the glibmm switch to C++14 yet, maybe someone can shed some light on this.

Best,
Flössie

**Comment by Floessie** [comment]
The C++14 construct was included in glibmm 2.54 [accidentally](https://bugzilla.gnome.org/show_bug.cgi?id=787648). Should be fixed in [2.54.1](https://mail.gnome.org/archives/ftp-release-list/2017-September/msg00194.html).

Closing,
Flössie
