### ISSUE TITLE
Can't build on OS X 10.9 (clang vs gcc issue)

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2286]
Originally reported on Google Code with ID 2302

```
Note: I'm not a mac guru, (I'm a linux guy), I just happen to have a mac at work. My
10.7 build box crashed a while ago, and I'm currently using 10.9.

In 10.9 macports started using clang instead of gcc as default compiler. RT must be
compiled with gcc because clang does not implement openmp, which RT relies heavily
upon.

As it seems, there's some C++ linking issues, for example the Glib::Checksum::compute_checksum
won't link due to undefined symbol. I tried both compilers and GCC generates a different
symbol than Clang does, which means that the GCC-compiled object file cannot link to
the Clang-compiled library.

I don't have any solution for this problem, so my mac builds are stuck...
```

Reported by `torger@ludd.ltu.se` on 2014-03-19 18:07:14
